[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chimera/=lib/chimera/src/", "@crytic/=lib/properties/contracts"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# Ensure the optimizer is enabled
optimizer = true
optimizer_runs = 200
coverage = true

[invariant]
runs = 0