[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chimera/=lib/chimera/src/", "@crytic/=lib/properties/contracts"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# Ensure the optimizer is enabled
optimizer = true
optimizer_runs = 200
coverage = true

no_match_path = "test/invariant/*"
no_match_contract = "CryticTester|CryticToFoundry|FoundryHandler"

[invariant]
no_match_path = "a^"
match_contract = "FoundryTester"
fail_on_revert = false
show_progress = true
